"""Add stamp rally tables

Revision ID: 0f033d773525
Revises: c163da960e31
Create Date: 2026-01-07 05:37:39.236686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0f033d773525'
down_revision: Union[str, None] = 'c163da960e31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prefecture_stamps',
    sa.Column('prefecture_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_romaji', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('prefecture_code')
    )
    op.create_index(op.f('ix_prefecture_stamps_display_order'), 'prefecture_stamps', ['display_order'], unique=False)
    op.create_index(op.f('ix_prefecture_stamps_is_active'), 'prefecture_stamps', ['is_active'], unique=False)
    op.create_index(op.f('ix_prefecture_stamps_name'), 'prefecture_stamps', ['name'], unique=False)
    op.create_index(op.f('ix_prefecture_stamps_name_romaji'), 'prefecture_stamps', ['name_romaji'], unique=False)
    op.create_index(op.f('ix_prefecture_stamps_region'), 'prefecture_stamps', ['region'], unique=False)
    op.create_table('user_stamp_collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('prefecture_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.Column('first_visit_date', sa.Date(), nullable=False),
    sa.Column('last_visit_date', sa.Date(), nullable=False),
    sa.Column('unique_farms_count', sa.Integer(), nullable=False),
    sa.Column('total_nights', sa.Integer(), nullable=True),
    sa.Column('total_experience_types', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['prefecture_code'], ['prefecture_stamps.prefecture_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guest_id', 'prefecture_code', name='uix_guest_prefecture')
    )
    op.create_index(op.f('ix_user_stamp_collection_first_visit_date'), 'user_stamp_collection', ['first_visit_date'], unique=False)
    op.create_index(op.f('ix_user_stamp_collection_guest_id'), 'user_stamp_collection', ['guest_id'], unique=False)
    op.create_index(op.f('ix_user_stamp_collection_last_visit_date'), 'user_stamp_collection', ['last_visit_date'], unique=False)
    op.create_index(op.f('ix_user_stamp_collection_prefecture_code'), 'user_stamp_collection', ['prefecture_code'], unique=False)
    op.create_table('user_stamp_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('prefecture_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('experience_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['guest_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['prefecture_code'], ['prefecture_stamps.prefecture_code'], ),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id')
    )
    op.create_index('idx_guest_prefecture_date', 'user_stamp_detail', ['guest_id', 'prefecture_code', 'visit_date'], unique=False)
    op.create_index(op.f('ix_user_stamp_detail_farm_id'), 'user_stamp_detail', ['farm_id'], unique=False)
    op.create_index(op.f('ix_user_stamp_detail_guest_id'), 'user_stamp_detail', ['guest_id'], unique=False)
    op.create_index(op.f('ix_user_stamp_detail_prefecture_code'), 'user_stamp_detail', ['prefecture_code'], unique=False)
    op.create_index(op.f('ix_user_stamp_detail_visit_date'), 'user_stamp_detail', ['visit_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_stamp_detail_visit_date'), table_name='user_stamp_detail')
    op.drop_index(op.f('ix_user_stamp_detail_prefecture_code'), table_name='user_stamp_detail')
    op.drop_index(op.f('ix_user_stamp_detail_guest_id'), table_name='user_stamp_detail')
    op.drop_index(op.f('ix_user_stamp_detail_farm_id'), table_name='user_stamp_detail')
    op.drop_index('idx_guest_prefecture_date', table_name='user_stamp_detail')
    op.drop_table('user_stamp_detail')
    op.drop_index(op.f('ix_user_stamp_collection_prefecture_code'), table_name='user_stamp_collection')
    op.drop_index(op.f('ix_user_stamp_collection_last_visit_date'), table_name='user_stamp_collection')
    op.drop_index(op.f('ix_user_stamp_collection_guest_id'), table_name='user_stamp_collection')
    op.drop_index(op.f('ix_user_stamp_collection_first_visit_date'), table_name='user_stamp_collection')
    op.drop_table('user_stamp_collection')
    op.drop_index(op.f('ix_prefecture_stamps_region'), table_name='prefecture_stamps')
    op.drop_index(op.f('ix_prefecture_stamps_name_romaji'), table_name='prefecture_stamps')
    op.drop_index(op.f('ix_prefecture_stamps_name'), table_name='prefecture_stamps')
    op.drop_index(op.f('ix_prefecture_stamps_is_active'), table_name='prefecture_stamps')
    op.drop_index(op.f('ix_prefecture_stamps_display_order'), table_name='prefecture_stamps')
    op.drop_table('prefecture_stamps')
    # ### end Alembic commands ###
