version: '3.8'

services:
  workspace:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/workspace:cached
    command: sleep infinity
    networks:
      - farm-match-network
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://farmatch:farmatch_dev@db:5432/farmatch_db
      - NODE_ENV=development

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: farmatch
      POSTGRES_PASSWORD: farmatch_dev
      POSTGRES_DB: farmatch_db
    networks:
      - farm-match-network
    ports:
      - "5432:5432"

networks:
  farm-match-network:
    driver: bridge

volumes:
  postgres-data:
